spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/creatorFund?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Rithinsai@81}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
