spring.application.name=CreatorFund

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/creatorFund?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Rithinsai@81
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Schema Initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
